Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using StopHunger.Models;

namespace StopHunger.Controllers
{
    public class ProductController : Controller
    {
        private int? uid
        {
            get
            {
                return HttpContext.Session.GetInt32("UserId");
            }
        }

        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }

        private StopHungerContext db;
        public ProductController(StopHungerContext context)
        {
            db = context;
        }


        [HttpGet("/product")]
        public IActionResult All()
        {
            if (!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            List<Product> products = db.Products
                .Include(p => p.CreatedBy)
                .ToList();

            return View("All", products);
        }

        [HttpGet("/products/new")]
        public IActionResult New()
        {
            if (!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            return View("New");
        }

        [HttpPost("/products/create")]
        public IActionResult Create(Product newProduct)
        {
            if (!ModelState.IsValid)
            {
                // To display validation errors.
                return View("New");
            }


            // WILL GET THIS ERROR if FK is not assigned:
            // "foreign key constraint fails"
            newProduct.UserId = (int)uid;
            db.Products.Add(newProduct);
            db.SaveChanges(); // after this newTrip has it's TripId from DB.

            /* 
            WHENEVER REDIRECTING to a method that has params, you must pass in
            a 'new' dictionary: new { paramName = valueForParam }
            */
            return RedirectToAction("Details", new { productId = newProduct.ProductId });
        }

        [HttpGet("/products/{productId}")]
        public IActionResult Details(int productId)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            Product product = db.Products
                .Include(p => p.CreatedBy)
                .Include(p => p.ProductDonutions)
                .ThenInclude(td => td.ShelterInfoType)
                .FirstOrDefault(p=> p.ProductId == productId);

            if (product == null)
            {
                return RedirectToAction("New");
            }

            List<ShelterInfoType> allDonations = db.ShelterInfoType.ToList();
            List<ShelterInfoType> unrelatedDonations = new List<ShelterInfoType>();

            foreach (ShelterInfoType donat in allDonations)
            {
                bool isRelated = product.ProductDonutions
                    .Any(pd => pd.ShelterInfoTypeId == donat.ShelterInfoTypeId);

                if (!isRelated)
                {
                    unrelatedDonations.Add(donat);
                }
            }

            ViewBag.UnrelatedDonations = unrelatedDonations

                .OrderBy(donat => donat.Location, System.StringComparer.CurrentCultureIgnoreCase);

            return View("Details", product);
        }

        [HttpGet("/products/{productId}/edit")]
        public IActionResult Edit(int productId)
        {
            Product product = db.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product == null || product.UserId != uid)
            {
                return RedirectToAction("All");
            }

            return View("Edit", product);
        }

        [HttpPost("/products/{productId}/update")]
        public IActionResult Update(Product editedProduct, int productId)
        {
            if (!ModelState.IsValid)
            {
                /* 
                "Object reference not set to an instance of an object" if we
                don't pass the editedTrip back with the TripId because the form
                has asp-route-tripId="@Model.TripId" so it needs the TripId.
                */
                editedProduct.ProductId = productId;
                // Go back to form to display errors.
                return View("Edit", editedProduct);
            }

            Product dbProduct= db.Products.FirstOrDefault(t => t.ProductId == productId);

            if (dbProduct == null)
            {
                return RedirectToAction("All");
            }

            dbProduct.UpdatedAt = DateTime.Now;
            dbProduct.Categorie = editedProduct.Categorie;
            dbProduct.Name = editedProduct.Name;
            dbProduct.Description = editedProduct.Description;
            dbProduct.Quantity = editedProduct.Quantity;
            dbProduct.Price = editedProduct.Price;
            dbProduct.Date = editedProduct.Date;

            db.Products.Update(dbProduct);
            db.SaveChanges();

            /* 
            WHENEVER REDIRECTING to a method that has params, you must pass in
            a 'new' dictionary: new { paramName = valueForParam }
            */
            return RedirectToAction("Details", new { productId = dbProduct.ProductId });
        }

        [HttpPost("/products/{productId}/delete")]
        public IActionResult Delete(int productId)
        {
            Product product = db.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product == null)
            {
                return RedirectToAction("All");
            }

            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("All");
        }

        [HttpPost("/products/{productId}/add-donation")]
        public IActionResult AddDonation(ProductDonutionToShelter newDonation, int productId)
        {
            db.ProductDonutionToShelters.Add(newDonation);
            db.SaveChanges();
            return RedirectToAction("Details", new { productId = productId });
        }

        [HttpPost("/product/{productId}")]
        public IActionResult Donate(int productId)
        {
            if (!isLoggedIn)// checking to see is user loggedin or not
            {
                return RedirectToAction("Index", "Home");
            }

            UserProductDonation existingdonation = db.UserProductDonations
                .FirstOrDefault(d => d.UserId == uid && d.ProductId == productId);

            if (existingdonation == null)
            {
                UserProductDonation donate = new UserProductDonation()
                {
                    ProductId = productId,
                    UserId = (int)uid
                };

                db.UserProductDonations.Add(donate);
            }
            else
            {
                db.UserProductDonations.Remove(existingdonation);
            }
            db.SaveChanges();
            return RedirectToAction("Details");
        }
    }
}

Controllers/ShelterInfoTypeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using StopHunger.Models;

namespace StopHunger.Controllers
{
    public class ShelterInfoTypeController : Controller
    {
        private int? uid
        {
            get
            {
                return HttpContext.Session.GetInt32("UserId");
            }
        }

        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }

        private StopHungerContext db;
        public ShelterInfoTypeController(StopHungerContext context)
        {
            db = context;
        }


        [HttpGet("/donations/new")]
        public IActionResult New()
        {
            if (!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            return View("New");
        }

        [HttpPost("/donation/create")]
        public IActionResult Create(ShelterInfoType newShelterInfoType)
        {
            if (!ModelState.IsValid)
            {
                // To display validation errors.
            Console.WriteLine("New donation");
                return View("New");
            }
            newShelterInfoType.UserId = (int)uid;
            db.ShelterInfoType.Add(newShelterInfoType);
            db.SaveChanges();

            return RedirectToAction("Details", new { ShelterInfoTypeId = newShelterInfoType.ShelterInfoTypeId });
        }

        [HttpGet("/shelters/{ShelterInfoTypeId}")]
        public IActionResult Details(int shelterInfoTypeId)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            ShelterInfoType shelterInfoType = db.ShelterInfoType
                .FirstOrDefault(s => s.ShelterInfoTypeId == shelterInfoTypeId);

            if (shelterInfoType == null)
            {
                return RedirectToAction("New");
            }

            return View("Details", shelterInfoType);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/ShelterInfoType/Details.cshtml
@model ShelterInfoType

@{
    ViewData["Title"] = "Donation Details";
    int? uid = @Context.Session.GetInt32("UserId");
}

<div class="w-75 mx-auto">
    <h2>@Model.Location</h2>
    <small>@Model.Location - @Model.ShortDescription</small>

    @if (@Model.Type == "Image")
    {
        <img src="@Model.Src" alt="@Model.ShortDescription" width="100%">
    }
    else if (@Model.Type == "Youtube Embed")
    {
        <iframe width="100%" height="800" src="@Model.Src" title="@Model.ShortDescription" frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen></iframe>
    }
    else
    {
        <iframe title="@Model.ShortDescription" src="@Model.Src" width="100%" height="800" style="border:0;"
        allowfullscreen="" loading="lazy"></iframe>
    }

    @if (uid == Model.UserId)
    {
        <div>
            <button class="btn btn-sm btn-outline-warning">Edit</button>
            <button class="btn btn-sm btn-outline-danger">Delete</button>
        </div>
    }
    @* <div>
    <partial name="_AddDonation"/></div> *@
</div>

Views/ShelterInfoType/New.cshtml
@model ShelterInfoType

@{
    ViewData["Title"] = "New Donation Destination";
}

<div class="w-50 mx-auto">
    <h2 class="text-center">New Donation Destination</h2>

    <form asp-controller="ShelterInfoType" asp-action="Create" method="POST">
        <div class="form-group">
            <label asp-for="Name"></label>
            <span asp-validation-for="Name" class="text-danger font-weight-bold"></span>
            <input asp-for="Name" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Location"></label>
            <span asp-validation-for="Location" class="text-danger font-weight-bold"></span>
            <input asp-for="Location" class="form-control">
        </div>

        <div class="form-group">
            <label asp-for="Src"></label>
            <span asp-validation-for="Src" class="text-danger font-weight-bold"></span>
            <input asp-for="Src" class="form-control">
        </div>

        <div class="form-group">
            <label asp-for="Type"></label>
            <span asp-validation-for="Type" class="text-danger font-weight-bold"></span>
            <select asp-for="Type" class="form-control">
                <option value="Image">Image</option>
                @* <option value="Youtube Embed">Youtube Embed</option> *@
                <option value="Google Maps Embed">Google Maps Embed</option>
                <option value="Website Embed">Website Embed</option>
            </select>
        </div>
        <div class="form-group">
            <label asp-for="ShortDescription"></label>
            <span asp-validation-for="ShortDescription" class="text-danger font-weight-bold"></span>
            <textarea asp-for="ShortDescription" class="form-control" cols="30" rows="5"></textarea>
        </div>
        <button class="btn btn-sm btn-outline-success">Submit</button>
    </form>
</div>

Views/ShelterInfoType/_AddDonation.cshtml
@* For creating a new many to many relationship between Product and Shelter *@
@model ProductDonutionToShelter

<form asp-controller="Product" asp-action="AddDonation" asp-route-productId="@Model.ProductId" method="POST">
    <select asp-for="ShelterInfoTypeId" class="form-control">
        @foreach (ShelterInfoType donat in ViewBag.UnrelatedDonations)
        {
                        <option value="@donat.ShelterInfoTypeId">@donat.Location - @donat.ShortDescription</option>
        }
    </select>
    <button class="btn btn-sm btn-outline-secondary mt-1">Add</button>
</form>